### ISSUE TITLE
script API error is not transmitted to the browser context

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/cloud-issues#10]
# Background
When script loading errors (f.e.) - the whole http resource returns a 4xx error.  As described in https://cloud.51degrees.com/api-docs/index.html.  Besides 4xx status it returns the body that is supposed to be running in the context of the <script> tag in the browser.   F.e. if you try to use an invalid key:

```http
GET https://cloud.51degrees.com/api/v4/invalid.js 
```
You get this response body (with a status 400):

```js
var fod = new Object(); fod.errors = ["'invalid' is not a valid Resource Key. See http://51degrees.com/documentation/_info__error_messages.html#Resource_key_not_valid for more information."];
```

# Problem
While you can see the body when doing direct request in the browser or f.e. curl - if you do this in the <script> tag - this response body is  just discarded and is never executed in the context of the browser.  Thus you lose the error info entirely. 
You can check this if you put it within a test page.

![image](https://user-images.githubusercontent.com/341967/214036111-e7cab5d4-f303-44a8-9798-8c3d091bf774.png)

![image](https://user-images.githubusercontent.com/341967/214036218-fbe7a974-35fb-47b7-9000-b23544c224b6.png)

The response is just discarded and `fod` object is undefined. 

# Potential Solution
I think browsers will only execute script if it returns status 2xx, so perhaps we can sacrifice the response code in order to propagate the error to the script context for this resource.  This behavior can be documented in the API doc for the developer to handle properly fod.errros (see another issue about respecting custom fod object name: #9 in case of error).

Of course this can't be done in case request handling on the server was out of our control - f.e. there was a network issue and the request timed out or 500 Server Error happened while handling the request - in these cases the browser would just not load the script, so it is a different class of error.

**Comment by ben51degrees** [comment]
Hi @justadreamer ,
As this scenario should only be happening during development, we have decided to keep 400 response code.
Having the request fail completely should make it more obvious that the call is not set up correctly. And while this does come at the expense of the error message being available, this is hopefuly mitigated by the fact that it will be in development, so the developer won't have a hard time just manually looking at the response.

Thanks,
Ben
