### ISSUE TITLE
cloud script sometimes confuses mac with the iPad (when zoomed to 200% on the external monitor on the mac)

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/cloud-issues#12]
Can be observed using client script generated by the configurator and a regular resource key obtained thru this link: https://configure.51degrees.com/S6fGMDKw 

These properties are included: 
![image](https://user-images.githubusercontent.com/341967/217013512-5daeb603-fef5-45aa-bc0e-2a58abfd00e6.png)

See the video demo:  https://take.ms/nq9w0

Depending on the scale:

- when it is 200%:
```
HardwareModel: iPad 7
HardwareName: iPad (9th Gen.),iPad 7,iPad 8
DeviceType: Tablet
```

- when it is less: 
```
HardwareModel: Macintosh
HardwareName: Macintosh
DeviceType: Desktop
```
(need to refresh without cache: cmd+shift+R on a mac so that the script reloads):

The hypothesis is: looks like `javascripthardwareprofile` is overriding the platformname in the evidence (which is macOS) and based on the viewport properties assumes it is iPad.

**Comment by Steve51D** [comment]
Thanks for the information.
This is an interesting one, and I'm not sure if we can do much about it.
I'll raise it for discussion internally and update here once we have a way forward.

**Comment by Steve51D** [comment]
Hi @justadreamer,

This is caused by the properties of the browser window at that zoom level happening to align with the listed iPads.
We've discussed this and we feel that it's an extreme edge case that, if it's even possible to address, wouldn't be worth the effort.
