### ISSUE TITLE
iPhone 12 Pro Max model detection is broken on the client

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/cloud-issues#13]
# Actual behavior

## Environment
Google Chrome for iOS version 109.0.5414.112

## Setup
I've created a Resource Key following the link: https://configure.51degrees.com/S6fGMDKw - it has some properties preselected including a `JavascriptHardwareProfile`.  

I then ran the html snippet provided on the last page of the configurator on my iOS device (hosted on a local vite server with a self-signed certificate) 

## Result
I get a super wide range of hardware models:

```json
"hardwarename": [
			"iPhone",
			"iPhone 11",
			"iPhone 11 Pro",
			"iPhone 11 Pro Max",
			"iPhone 12",
			"iPhone 12 Pro",
			"iPhone 12 Pro Max",
			"iPhone 12 mini",
			"iPhone 13",
			"iPhone 13 Pro",
			"iPhone 13 Pro Max",
			"iPhone 13 mini",
			"iPhone 14",
			"iPhone 14 Plus",
			"iPhone 14 Pro",
			"iPhone 14 Pro Max",
			"iPhone 3G",
			"iPhone 3GS",
			"iPhone 4",
			"iPhone 4S",
			"iPhone 5",
			"iPhone 5S",
			"iPhone 5c",
			"iPhone 6",
			"iPhone 6 Plus",
			"iPhone 6s",
			"iPhone 6s Plus",
			"iPhone 7",
			"iPhone 7 Plus",
			"iPhone 8",
			"iPhone 8 Plus",
			"iPhone SE",
			"iPhone SE (2nd Gen.)",
			"iPhone SE (3rd Gen.)",
			"iPhone X",
			"iPhone XR",
			"iPhone XS",
			"iPhone XS Max"],
```

# Expected
Run html code and get a narrow range of hardware device models in the browser according to https://51degrees.com/documentation/4.4/_device_detection__features__apple_device_table.html 

I used to get this list of models before:  iPhone 12 Pro Max, iPhone 13 Pro Max, iPhone 14 Plus

**Comment by Steve51D** [comment]
Hi,

We think we have identified the problem. Hoping to have this addressed in a fix in the new data files tomorrow (14th Feb)

**Comment by justadreamer** [comment]
Seems to be fixed now.  Thank you. 

![IMG_B80B14DBD18D-1](https://user-images.githubusercontent.com/341967/219058644-efe5a78a-8935-4bf3-841c-89455a058d10.jpeg)

**Comment by Steve51D** [comment]
Ah, Thanks for the update! I was just testing this and struggling to understand why it didn't seem to be working.
I think there is a similar, but separate, issue that happens when using things like Chrome developer tools to emulate iPhones.

**Comment by justadreamer** [comment]
yes, that test was from a physical device, getting this via dev tools: 

![image](https://user-images.githubusercontent.com/341967/219087259-dded5cfb-2ec6-4eb8-b61f-7b06b8bfc6de.png)

**Comment by Steve51D** [comment]
Interesting. Thanks. Perhaps I'm running into some sort of caching issue with my tests then.
In any case, I'll close this for now, as the specific problem is clearly resolved.
