### ISSUE TITLE
Cloud documentation JS examples do not show error message in response

### ISSUE THREAD

**Issue by Joseph51D** [51Degrees/cloud-issues#4]
In the [cloud api-docs](https://cloud.51degrees.com/api-docs/index.html), the examples where the media type is `application/javascript` do not show the error message returned in the response when a request fails with a non 2xx/3xx status code.

**Comment by Steve51D** [comment]
This seems to be beyond the ability of Swashbuckle.
As described by this [SO answer](https://stackoverflow.com/questions/42974559/swashbuckle-define-response-body-on-error)

> you can't return a text in the schema definition. It is there for json structures, not for error messages. Instead you should use xmldoc (and also enable it in swagger) to add descriptions to the parameters.

When a 401 occurs, this endpoint will return the content:
```
var fod = new Object(); fod.errors = [\"FiftyOne.Pipeline.CloudService.Messages._400InvalidRequest\"];
```

We could fudge it to show something like:

```
{
  "content": "var fod = new Object(); fod.errors = [\"FiftyOne.Pipeline.CloudService.Messages._400InvalidRequest\"];"
}
```

However, I don't think this is helpful as it implies json will be returned when it will just be plain JavaScript.
We could edit the end point summary section to include the content returned for error responses, but that's not really where you would expect the information to be.

**Comment by Steve51D** [comment]
We will not be addressing this problem at this time. If this issue impacts you then please re-open and we will look again at what changes we could make.
