### ISSUE TITLE
Cloud documentation AccessibleProperties

### ISSUE THREAD

**Issue by jwrosewell** [51Degrees/cloud-issues#5]
[AccessibleProperties](https://cloud.51degrees.com/api/v4/AccessibleProperties) API example gives this response.

{
  "status": "401",
  "errors": [
    "A resource key is required to access the 51Degrees Cloud Service. See http://51degrees.com/documentation/_info__error_messages.html#Resource_key_required  for more information."
  ]
}

However the documentation example does not provide an field for the resource key.

**Comment by jorabin-51d** [comment]
Please see https://cloud.51degrees.com/api-docs/index.html where it describes that a resource key must be supplied as  a parameter. Other calls make the resource key part of the URL.
