### ISSUE TITLE
feature suggestion: implement /api/v4/metadata endpoint

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/cloud-issues#6]
# Motivation

To design a business logic that is relying on the cloud API around property metadata and in particular value range.

# Background

There is `/api/v4/AccessibleProperties` endpoint - it returns available properties for a given resource key, however the user might be interested in a value range for a given property.

# Endpoint
## Success
Provide a `GET /api/v4/metadata` endpoint that would take the params:

- `resource` - a resource key like /api/v4/AccessibleProperties takes
- `property` - a property name 

A successful response should include:

```js
{
"status": 200,
"component":, 
"property":, 
"description":,
"values": [...]
}
``` 

These fields in the response object correspond to the columns of the metadata CSV file. 

## Failure

A 404 can be returned for an invalid property name:

```js
{
"errors": [ "No such property"], 
"status": "404"
}
```

or 400-401 for a wrong or missing `resource`:
```
{
    "errors": [
        "A resource key is required to access the 51Degrees Cloud Service. See http://51degrees.com/documentation/_info__error_messages.html#Resource_key_required  for more information."
    ],
    "status": "401"
}


{
    "errors": [
        "'2342342' is not a valid Resource Key. See http://51degrees.com/documentation/_info__error_messages.html#Resource_key_not_valid for more information."
    ],
    "status": "400"
}
```

**Comment by Steve51D** [comment]
Hi @justadreamer,

Thanks for the suggestion. We had previously considered a similar change internally. However, we decided not to implement it, since it seemed that none of our cloud customers had any desire or need for this extra meta data.

Could you expand a bit on your use case so we can evaluate how to prioritize this?

Also, I see you mention the value range as particularly interesting. However, this is probably the most problematic field. Some properties don't have many possible values, but others have over 100,000.
That's obviously not an insurmountable amount of data, but it's fairly chunky for something that is otherwise a very lightweight web API.

**Comment by justadreamer** [comment]
Hi @Steve51D 

You raise great points!  The use case I faced was in particular dealing with the `DeviceType` data point - I needed to know what are the possible values of this data point to specify behavior in the library code that I am currently working on depending on the device type. 

So the motivation for the user can be:

- not only display the value straight as it is returned, but adapt it to some human readable format
- based on the value perform some side effects, f.e. if it is `Tv` - we provide one content, if it is `Desktop` or `Mobile` - the other.

This obviously can deal not only with the `DeviceType`, but with other data points as well.  So it comes down to some mapping of the returned values either thru a value/action table or thru if-else/switch conditional logic in code.   However the code ideally must exhaust the value range or at least span a significant part of it with the default behavior for the not spanned range.  

## Large responses

You raise a great point that some data points have over 100k possible values, and listing all of them is concerning as it opens up some possibilities for API abuse.  On the other hand for 100k possible values it is hard to come up with a mapping code logic - so maybe it is not that necessary either.  So if values can not be represented as a range and need to be listed out, there can be some response truncation logic - f.e. if there are more than X characters or Y values or response size would be more than 2KB etc. 

## Alternatives

This is essentially a "documentation" endpoint - so for main data points such as DeviceType or BrowserVendor - it could be partially solved by improving the documentation - just specifying the exhaustive list of values in the doc.   This has a downside that it might become obsolete, and would require adding or changing values, unlike the API code that I would assume would take them straight from the DB...

**Comment by Steve51D** [comment]
Hi @justadreamer,

We're not going to be actioning this one.
If people need a list of the possible values for each property, they can get it from the CSV files we provide.

While adding this to the cloud API would be a nice quality of life feature, we don't have the demand from customers to justify spending time on it at the moment.
