### ISSUE TITLE
cloud script API error snippet ignores custom fod-js-object-name

### ISSUE THREAD

**Issue by justadreamer** [51Degrees/cloud-issues#9]
A potential bug, or maybe it is by design, but still was a bit unexpected for us.  

# Actual behavior

The call to JS resource with an invalid resource key (or otherwise yielding an error) such as this:
```http
GET https://cloud.51degrees.com/api/v4/invalid.js?fod-js-object-name=FODCB
``` 
results in loading this snippet of code:
```js
var fod = new Object(); fod.errors = ["'invalid' is not a valid Resource Key. See http://51degrees.com/documentation/_info__error_messages.html#Resource_key_not_valid for more information."];
```

notice how it instantiates a `fod` object ignoring the `fod-js-object-name=FODCB` passed in the request.

# Expected behavior

The call mentioned above (or any other yielding an error) yields a snippet respecting the passed fod-js-object-name, i.e.:

```js
var FODCB = new Object(); FODCB.errors = ["'invalid' is not a valid Resource Key. See http://51degrees.com/documentation/_info__error_messages.html#Resource_key_not_valid for more information."];
```

**Comment by Steve51D** [comment]
This bug has been addressed in the latest cloud release earlier today. The problem was that the `fod-js-object-name` parameter was not being respected when certain failures occurred.
